name: Publish latest release to ghcr.io

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for tags

      - name: Fetch latest release tag from GitHub API
        run: |
          LATEST_TAG=$(curl -s https://api.github.com/repos/supermerill/SuperSlicer/releases/latest | jq -r '.tag_name')

          if [ -z "$LATEST_TAG" ] || [ "$LATEST_TAG" == "null" ]; then
            echo "ERROR: No valid release tag found!"
            exit 1
          fi

          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push versioned and latest Docker images
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockerfile/release
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.LATEST_TAG }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: Verify pushed images
        run: |
          docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.LATEST_TAG }}
          docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
